name: "Build iOS app"

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Run npm Install
        run: |
             npm i -g corepack
             npm install
             npm install --save-dev @react-native-community/cli

      - name: Install CocoaPods
        run: |
             sudo gem install cocoapods
             pod --version

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true

      - name: Install iOS dependencies
        run: |
             npx react-native config
             npx react-native doctor
             npx react-native doctor ios

      - name: Generate iOS files
        run: |
             npx @react-native-community/cli init FarmSurv
             cp -r FarmSurv/ios .
             rm -rf FarmSurv

      - name: Install Pods
        run: |
             cd ios
             pod install

      - name: Configure code signing
        run: |
             cd ios
             /usr/libexec/PlistBuddy -c "Set :objects:$(/usr/libexec/PlistBuddy -c "Print :objects:PBXNativeTarget:13B07F861A680F5B00A75B9A:buildConfigurationList" FarmSurv.xcodeproj/project.pbxproj | grep -o '[A-Z0-9]\{24\}'):buildSettings:CODE_SIGN_IDENTITY ''" FarmSurv.xcodeproj/project.pbxproj
             /usr/libexec/PlistBuddy -c "Set :objects:$(/usr/libexec/PlistBuddy -c "Print :objects:PBXNativeTarget:13B07F861A680F5B00A75B9A:buildConfigurationList" FarmSurv.xcodeproj/project.pbxproj | grep -o '[A-Z0-9]\{24\}'):buildSettings:CODE_SIGNING_REQUIRED NO" FarmSurv.xcodeproj/project.pbxproj
             /usr/libexec/PlistBuddy -c "Set :objects:$(/usr/libexec/PlistBuddy -c "Print :objects:PBXNativeTarget:13B07F861A680F5B00A75B9A:buildConfigurationList" FarmSurv.xcodeproj/project.pbxproj | grep -o '[A-Z0-9]\{24\}'):buildSettings:CODE_SIGNING_ALLOWED NO" FarmSurv.xcodeproj/project.pbxproj

      - name: Build application
        run: |
             cd ios
             xcodebuild -workspace FarmSurv.xcworkspace -scheme FarmSurv -configuration Debug -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14' build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

      - name: Upload application
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: ./ios/build/Debug-iphonesimulator/FarmSurv.app
          retention-days: 3
