name: "Build Android app"

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm i -g corepack
          npm install
          npm install --save-dev @react-native-community/cli

      - name: Generate Android files
        run: |
          npx @react-native-community/cli init FarmSurv --template react-native-template-typescript
          cp -r FarmSurv/android .
          rm -rf FarmSurv

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
          cache-dependency-path: android/**/*.gradle*

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Build Android App
        run: |
          cd android
          ./gradlew assembleDebug --no-daemon
        env:
          ANDROID_HOME: ${{ env.ANDROID_HOME }}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: android/app/build/outputs/apk/debug/app-debug.apk
          retention-days: 3
