name: "Build iOS app"

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Run npm Install
        run: |
             npm i -g corepack
             npm install

      - name: Install CocoaPods
        run: |
             cd ./ios
             pod install

      - name: Build application
        run: |
             cd ./ios
             xcodebuild -workspace FarmSurv.xcworkspace -scheme FarmSurv -configuration Debug -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14' build

      - name: Upload application
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: ./ios/build/Debug-iphonesimulator/FarmSurv.app
          retention-days: 3
