name: "Lint and Test"

on:
  workflow_dispatch:
  push:
    branches: [dev, development]
  pull_request:
    branches: [dev, development, master]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run linting
        run: npm run lint

      - name: Run tests with coverage
        run: npm test -- --coverage --watchAll=false

      - name: Upload test coverage
        uses: actions/upload-artifact@v3
        with:
          name: test-coverage
          path: coverage/
          retention-days: 7
